import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import api from '../api'
import { downloadReportFile } from '../downloadJob'

export default function MaintenanceHistoryPage() {
  const [history, setHistory] = useState([])
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(null)
  const [downloadProgress, setDownloadProgress] = useState(null) // {key, pct, step}
  const navigate = useNavigate()

  useEffect(() => {
    api.get('/maintenance/history').then((r) => { setHistory(r.data); setLoading(false) }).catch(() => setLoading(false))
  }, [])

  async function download(id, fmt, name, e) {
    e?.stopPropagation()
    const key = `${id}-${fmt}`
    if (downloading) return
    setDownloading(key)
    setDownloadProgress({ key, pct: 0, step: 'Starting…' })
    try {
      const filename = `report_${name || 'report'}.${fmt}`.replace(/\s+/g, '_')
      await downloadReportFile(id, fmt, filename, (pct, step) => setDownloadProgress({ key, pct, step }))
    } catch {
      alert('Download failed. Please try again.')
    } finally {
      setDownloading(null)
      setDownloadProgress(null)
    }
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Maintenance Report History</h1>
        <button onClick={() => navigate('/maintenance/generate')} className="btn-primary text-sm">+ New Report</button>
      </div>

      {loading && <p className="text-gray-400">Loading…</p>}

      {!loading && history.length === 0 && (
        <div className="card text-center py-12">
          <p className="text-gray-400 text-sm">No reports generated yet.</p>
          <button onClick={() => navigate('/maintenance/generate')} className="btn-primary mt-4">Generate your first report</button>
        </div>
      )}

      <div className="space-y-3">
        {history.map((r) => (
          <div key={r.id} className="card">
            <div className="flex flex-wrap items-center gap-4">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <h3 className="font-semibold text-gray-900 truncate">{r.project_name}</h3>
                  <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-medium">{r.project_code}</span>
                  <span className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-gray-600">{r.photo_count} photo{r.photo_count !== 1 ? 's' : ''}</span>
                </div>
                <p className="text-sm text-gray-500 mt-0.5">
                  {r.date_from} to {r.date_to} · generated by {r.generated_by} on{' '}
                  {new Date(r.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}{' '}
                  {new Date(r.created_at).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button disabled={!!downloading} onClick={(e) => download(r.id, 'docx', r.project_name, e)} className="btn-green text-xs py-1">⬇ Report (Word)</button>
                <button disabled={!!downloading} onClick={(e) => download(r.id, 'pdf', r.project_name, e)} className="btn-green text-xs py-1">⬇ Report (PDF)</button>
              </div>
            </div>

            {downloadProgress?.key?.startsWith(`${r.id}-`) && (
              <div className="mt-3">
                <div className="flex items-center justify-between text-xs text-gray-500 mb-1">
                  <span>{downloadProgress.step}</span>
                  <span>{downloadProgress.pct}%</span>
                </div>
                <div className="w-full bg-gray-100 rounded-full h-1.5">
                  <div
                    className="bg-green-600 h-1.5 rounded-full transition-all duration-300"
                    style={{ width: `${downloadProgress.pct}%` }}
                  />
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
